services:
  nodejs:
    build: .
    container_name: nodejs
    restart: unless-stopped
    env_file: .env
    environment:
      - JWTSECRET=$JWTSECRET
    ports:
      - "3000:3000"
    volumes:
      - ./db:/code/db
    command: node index.js
