name: Run tests

on: 
  push:
    branches: [master, main]
  pull_request:
    branches: [master, main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 18
      - run: echo "[]" > db.json
      - run: npm install
      - run: npm test
      - run: rm db.rm db.json -rf
