name: Run tests

on: 
  push:
    branches:
      - "**"
  pull_request:
    branches: [master, main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 18
      - name: Create db folder
        run: mkdir db
      - name: Intialize Survey db
        run: echo "[]" > db/surveyDB.jso
      - name: Initialize user db 
        run: echo "[]" > db/db.json
      - name: Build
        run: npm install
      - name: Run tests
        run: npm test
      - name: Clean filesystem
        run: rm db.rm db.json -rf
